name: CI with Checkstyle   
on:
  push: 
    branches: 
      - feature1  # Trigger on the feature/develop branch
 
jobs:
  build-and-check:  
    runs-on: ubuntu-latest   

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository 
        uses: actions/checkout@v2

      # Step 2: Set up JDK 21 (Fixed Distribution)
      - name: Set up JDK 21
        uses: actions/setup-java@v2

        with:
          java-version: '21'
          distribution: 'temurin'
 
      # Step 3: Extract git commit data
      - name: Extract git commit data
        id: commit-data 
        uses: rlespinasse/git-commit-data-action@v1.x
 
      # Step 4: Build with Maven 
      - name: Build with Maven 
        run: mvn clean install -DskipTests
 
      # Step 5: JUnit tests
      - name: JUnit tests
        run: mvn test
